# Generated by Django 6.0.7 on 2026-07-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_name', models.CharField(max_length=200)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_price', models.DecimalField(decimal_places=2, help_text='Your estimate of current market value (used for unrealized profit).', max_digits=12)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('sold', 'Sold')], default='holding', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('skin_name', models.CharField(blank=True, max_length=200)),
                ('marketplace', models.CharField(blank=True, choices=[('csfloat', 'CSFloat'), ('buff163', 'Buff163'), ('steam', 'Steam Community Market'), ('skinport', 'Skinport'), ('other', 'Other')], max_length=20)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('marketplace_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('other_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_transactions', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
