# Generated by Django 6.0.7 on 2026-07-17 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('holding', 'Holding'), ('sold', 'Sold'), ('traded', 'Traded')], default='holding', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('p2p', 'P2P Trade')], max_length=10),
        ),
        migrations.CreateModel(
            name='P2PTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('given_skin_name', models.CharField(blank=True, max_length=200)),
                ('given_value', models.DecimalField(decimal_places=2, help_text='Agreed value of the skin you gave (for P&L tracking).', max_digits=12)),
                ('received_skin_name', models.CharField(max_length=200)),
                ('received_value', models.DecimalField(decimal_places=2, help_text='Agreed value of the skin you received.', max_digits=12)),
                ('cash_direction', models.CharField(choices=[('none', 'No cash involved (pure swap)'), ('received', 'I received extra cash'), ('paid', 'I paid extra cash')], default='none', max_length=10)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cash top-up paid or received on top of the skin swap.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_item', models.ForeignKey(blank=True, help_text='Skin from your inventory that you gave up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_given', to='core.inventoryitem')),
                ('received_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_received', to='core.inventoryitem')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
